In [2]:
import numpy as np

In [ ]:
array = np.arange(10, 20)
# We can call or general function of numpy, or methods of arrays directly
print(np.sum(array))
print(array.sum())
print(np.mean(array))
print(array.mean())
print(np.min(array))
print(array.min())
print(np.max(array))
print(array.max())

145
145
14.5
14.5
10
10
19
19


In [11]:
array = np.random.rand(1000).astype(np.float64)
print(np.sum(array))
print(array.sum())
print(np.mean(array))
print(array.mean())
print(np.min(array))
print(array.min())
print(np.max(array))
print(array.max())

503.68099982241995
503.68099982241995
0.50368099982242
0.50368099982242
0.0007511024560163948
0.0007511024560163948
0.9995652304657051
0.9995652304657051


In [18]:
array = np.ones((5, 5), dtype=int)
print(array[:, 1])
print(array[1])
print(array.flatten())


[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [21]:
array = np.random.rand(500000)
print(np.sum(array))
print(array.sum())
print(np.mean(array))
print(array.mean())
print(np.min(array))
print(array.min())
print(np.max(array))
print(array.max())

250081.7812439971
250081.7812439971
0.5001635624879942
0.5001635624879942
4.167940883759158e-06
4.167940883759158e-06
0.9999985627978593
0.9999985627978593
