In [1]:
import numpy as np

In [3]:
array = np.array([12, -5, 7, 9, -3, 15])
array = np.append(array, 10)
array

array([12, -5,  7,  9, -3, 15, 10])

In [5]:
array = np.array([
    [5, 2, 8],
    [1, 7, 4],
    [3, 6, 9]
])
array = np.delete(array, 1, axis=0)
array

array([[5, 2, 8],
       [3, 6, 9]])

In [11]:
conversions = np.array([50, 65, 80, 45, 70, 90, 55, 85, 60, 75])
print(conversions)

print(np.median(conversions))
print(np.var(conversions))
print(np.std(conversions))

array1 = np.random.rand(5)
array2 = np.random.randint(1, 11, size=5)
array3 = np.random.uniform(5, 15, size=5)
array4 = np.random.normal(0, 1, size=5)

combined_conversions = np.concatenate([conversions, array1, array2, array3, array4])
print(combined_conversions)

mean_of_combined_conversions = combined_conversions.mean()
print(mean_of_combined_conversions)
print(mean_of_combined_conversions > 2000)


[50 65 80 45 70 90 55 85 60 75]
67.5
206.25
14.361406616345072
[50.         65.         80.         45.         70.         90.
 55.         85.         60.         75.          0.89496025  0.68088716
  0.20568603  0.90074315  0.46298768  6.          6.         10.
  8.          8.          8.87151556 11.95697732  7.03262663 14.96097072
  6.20129613 -0.25711833 -0.11453465  2.53999101 -0.25665166  1.24093177]
25.610708958727585
False
