In [1]:
import numpy as np

In [7]:
array1 = np.random.randint(-10, 11, size=(4, 4))
array2 = np.random.randint(-10, 11, size=(4, 4))
array3 = np.random.randint(-10, 11, size=(4, 4))
array = np.stack([array1, array2, array3], axis=0)
assert array.shape == (3, 4, 4)


In [11]:
B = np.random.randint(1, 10, (2, 3, 4))
print("Оригінальний тривимірний масив B:\\n", B)

# Перетворення у двовимірний масив
B_reshaped = np.reshape(B, shape=(6, 4))
print("Масив після зміни форми:\\n", B_reshaped)

# Перетворення у одновимірний
B_flattened = np.ravel(B)
# Or
# B_flattened = B.flatten()
print("Одновимірний масив:\\n", B_flattened)

Оригінальний тривимірний масив B:\n [[[5 8 1 7]
  [3 2 6 5]
  [6 1 4 9]]

 [[3 6 6 9]
  [9 7 5 1]
  [3 1 9 1]]]
Масив після зміни форми:\n [[5 8 1 7]
 [3 2 6 5]
 [6 1 4 9]
 [3 6 6 9]
 [9 7 5 1]
 [3 1 9 1]]
Одновимірний масив:\n [5 8 1 7 3 2 6 5 6 1 4 9 3 6 6 9 9 7 5 1 3 1 9 1]


In [12]:
C = np.random.randint(1, 10, (3, 3, 3))
print("Оригінальний масив C:\\n", C)

# Сума по першій осі
sum_axis0 = C.sum(axis=0)
print("Сума по осі 0:\\n", sum_axis0)

# Сума по другій осі
sum_axis1 = C.sum(axis=1)
print("Сума по осі 1:\\n", sum_axis1)

# Загальна сума
total_sum =C.sum()
print("Загальна сума елементів масиву:", total_sum)

Оригінальний масив C:\n [[[9 2 7]
  [7 8 9]
  [1 3 3]]

 [[7 5 1]
  [1 9 6]
  [9 2 9]]

 [[1 2 9]
  [2 4 3]
  [6 2 8]]]
Сума по осі 0:\n [[17  9 17]
 [10 21 18]
 [16  7 20]]
Сума по осі 1:\n [[17 13 19]
 [17 16 16]
 [ 9  8 20]]
Загальна сума елементів масиву: 135
